import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sheard/Navbar";
import Footer from "@/components/sheard/Footer";
import WorkOutProvaider from "@/context/workOutContext";
import { Toaster } from "react-hot-toast";

const bebasNeue = Open_Sans({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Fit Log App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`$h-full antialiased`}
    >
      <body className={`${bebasNeue.className} min-h-full flex flex-col bg-[#0C0D10]`}>
        <WorkOutProvaider>
          <Navbar />
          <Toaster position="top-right" reverseOrder={true} />
          <div>{children}</div>
          <Footer />
        </WorkOutProvaider>
      </body>
    </html>
  );
}
